version: '3.8'

services:
  bind9:
    image: ubuntu/bind9:latest
    container_name: bind9
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - TZ=UTC
    volumes:
      - ./config/named.conf:/etc/bind/named.conf
      - ./records:/var/lib/bind
      - bind9cache:/var/cache/bind
    restart: unless-stopped
volumes:
  bind9cache: