- hosts: all
  become: yes

  tasks:
    - name: check whether ufw status is active
      shell: ufw status
      changed_when: False
      ignore_errors: True
      register: ufw_check

    - debug:
        msg: "{{ ufw_check }}"

    - name: do something if ufw is enabled
      shell: echo
      when: "'inactive' not in ufw_check.stdout"