version: '3.8'

services:
    mariadb:
        image: 'mariadb:latest'
        environment:
            - MYSQL_ROOT_PASSWORD=root
#            - MYSQL_DATABASE=tictactoe
            - MYSSQL_USER=sa
            - MYSQL_PASSWORD=root
        ports:
            - '3306:3306'
        container_name: mariadb
        networks:
           - tictactoe
networks:
  tictactoe:
    external: true