version: '3.8'

services:
    mosquitto:
        image: 'eclipse-mosquitto:latest'
        ports:
            - '1883:1883'
        container_name: mosquitto
        networks:
           - tictactoe
networks:
  tictactoe:
    external: true