name: Test VPN Connection

on:
  workflow_dispatch:

env:
  PING_HOST: 192.168.1.1
  VPN_OTP: ${{ secrets.VPN_OTP }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Timezone
        uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "Europe/Zurich"

      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt --assume-yes --no-install-recommends install openvpn oathtool

      - name: Setup VPN config
        run: | 
          echo "${{ secrets.VPN_CA_CRT }}" > ca.crt
          echo "${{ secrets.VPN_USERNAME_PASSWORD }}" > secret.txt

      - name: Add VPN TOTP
        run: |
          OTP=$(oathtool --totp ${{ secrets.VPN_OTP }})
          sed -i '$ s/$/'"$OTP"'/' secret.txt
        if: ${{ env.VPN_OTP != 0 }}

      - name: Connect VPN
        run: sudo openvpn --config ".github/vpn/config.ovpn" --log "vpn.log" --daemon

      - name: Wait for a VPN connection
        timeout-minutes: 1
        run: until ping -c1 ${{ env.PING_HOST }}; do sleep 2; done
        # OR
  #        run: until dig @your-dns-resolver your-server-address A +time=1; do sleep 2; done

      - name: Deploy
        run: ping ${{ env.PING_HOST }} -c5

      - name: Kill VPN connection
        if: always()
        run: | 
          sudo killall openvpn
          sudo chmod 777 vpn.log

      - name: Upload VPN logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: VPN logs
          path: vpn.log